spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FitnessApp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: your username
    password: your password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
